### PR TITLE
refactor(fetch/nvd): reduced memory by reading in stream

### PR DESCRIPTION
**Pull request by MaineK00n**
# What did you implement:

Until now, NVD Fetch has had problems such as high memory usage. This PR reduces memory usage.
The memory usage has been reduced from 3 GB to 400 MB.
Also, previously the JSON Feeds for each year were retrieved, but now the CPE Match Feed is retrieved.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
## before
```console
$ go-cpe-dictionary version
go-cpe-dictionary v0.5.0 59c88e6
$ /usr/bin/time -f "real(s): %e, memory(kB): %M" go-cpe-dictionary fetch nvd --batch-size 500
INFO[07-21|23:57:55] Inserting new CPEs 
1008164 / 1008164 [------------------------------------------] 100.00% 19523 p/s
INFO[07-21|23:58:47] Inserted 1008164 CPEs 
real(s): 126.02, memory(kB): 3061784
```

## after
```console
$ go-cpe-dictionary version
go-cpe-dictionary v0.5.0 a36553b
$ /usr/bin/time -f "real(s): %e, memory(kB): %M" go-cpe-dictionary fetch nvd --batch-size 500
...
INFO[07-21|23:54:50] Inserting new CPEs 
1046824 / 1046824 [------------------------------------------] 100.00% 18516 p/s
real(s): 104.32, memory(kB): 379104
```
# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

# Reference

### CODE REVIEW

**Comment by shigechika** [comment]
LGTM 👍 
-bofore
`real(s): 96.81, memory(kB): 3028232`
-after
`real(s): 97.29, memory(kB): 567884`

**Comment by shigechika** [comment]
```
$ go-cpe-dictionary version
go-cpe-dictionary v0.5.0 a36553b
$ go-cpe-dictionary fetch jvn
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2004.rdf
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2002.rdf
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2003.rdf
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2005.rdf
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2006.rdf
INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2007.rdf
INFO[07-26|11:58:32] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2008.rdf
INFO[07-26|11:58:32] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2009.rdf
INFO[07-26|11:58:34] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2010.rdf
INFO[07-26|11:58:36] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2011.rdf
INFO[07-26|11:58:36] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2012.rdf
INFO[07-26|11:58:38] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2013.rdf
INFO[07-26|11:58:39] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2014.rdf
INFO[07-26|11:58:40] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2015.rdf
INFO[07-26|11:58:41] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2016.rdf
INFO[07-26|11:58:45] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2017.rdf
INFO[07-26|11:58:48] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2018.rdf
INFO[07-26|11:58:49] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2019.rdf
INFO[07-26|11:58:55] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf
INFO[07-26|11:59:01] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf
INFO[07-26|11:59:05] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2022.rdf
INFO[07-26|11:59:06] Fetching... URL=https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf
INFO[07-26|11:59:06] Fetching... URL=https://jvndb.jvn.jp/ja/rss/jvndb.rdf
INFO[07-26|11:59:13] Deleting old CPEs
49148 / 49148 [---snip---] 100.00% 53737 p/s
INFO[07-26|11:59:14] Inserting new CPEs
0 / 49186 [___snip___] 0.00% ? p/s
```
freezing...

**Comment by MaineK00n** [comment]
> ```
> $ go-cpe-dictionary version
> go-cpe-dictionary v0.5.0 a36553b
> $ go-cpe-dictionary fetch jvn
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2004.rdf
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2002.rdf
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2003.rdf
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2005.rdf
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2006.rdf
> INFO[07-26|11:58:31] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2007.rdf
> INFO[07-26|11:58:32] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2008.rdf
> INFO[07-26|11:58:32] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2009.rdf
> INFO[07-26|11:58:34] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2010.rdf
> INFO[07-26|11:58:36] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2011.rdf
> INFO[07-26|11:58:36] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2012.rdf
> INFO[07-26|11:58:38] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2013.rdf
> INFO[07-26|11:58:39] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2014.rdf
> INFO[07-26|11:58:40] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2015.rdf
> INFO[07-26|11:58:41] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2016.rdf
> INFO[07-26|11:58:45] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2017.rdf
> INFO[07-26|11:58:48] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2018.rdf
> INFO[07-26|11:58:49] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2019.rdf
> INFO[07-26|11:58:55] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf
> INFO[07-26|11:59:01] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf
> INFO[07-26|11:59:05] Fetching... URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2022.rdf
> INFO[07-26|11:59:06] Fetching... URL=https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf
> INFO[07-26|11:59:06] Fetching... URL=https://jvndb.jvn.jp/ja/rss/jvndb.rdf
> INFO[07-26|11:59:13] Deleting old CPEs
> 49148 / 49148 [---snip---] 100.00% 53737 p/s
> INFO[07-26|11:59:14] Inserting new CPEs
> 0 / 49186 [___snip___] 0.00% ? p/s
> ```
> 
> freezing...

@shigechika 
fix this commit https://github.com/vulsio/go-cpe-dictionary/pull/81/commits/021b5060f46b0c9a1f262c42a9c967e415c587df

**Comment by shigechika** [comment]
I checked to working fine nvd and jvn at 021b506.
Thank you!
```
$ go-cpe-dictionary version
go-cpe-dictionary v0.5.0 021b506
$ go-cpe-dictionary fetch nvd
INFO[07-31|10:47:20] Fetching...                              URL=http://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz
INFO[07-31|10:47:43] Fetching...                              URL=https://nvd.nist.gov/feeds/json/cpematch/1.0/nvdcpematch-1.0.json.gz
INFO[07-31|10:47:57] Deleting old CPEs
1051489 / 1051489 [------------------------------------------] 100.00% 54526 p/s
INFO[07-31|10:48:16] Inserting new CPEs
1051489 / 1051489 [------------------------------------------] 100.00% 25193 p/s
$ go-cpe-dictionary fetch jvn
INFO[07-31|10:49:56] Fetching...                              URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2002.rdf
INFO[07-31|10:49:56] Fetching...                              URL=https://jvndb.jvn.jp/ja/rss/years/jvndb_2004.rdf
 :snip
INFO[07-31|10:50:24] Deleting old CPEs
49274 / 49274 [----------------------------------------------] 100.00% 56878 p/s
INFO[07-31|10:50:25] Inserting new CPEs
49274 / 49274 [----------------------------------------------] 100.00% 28102 p/s
```

**Review by kotakanbe — APPROVED** [review]

**Pull request merged**
